github: [ "matiqueue" ]
patreon: "matiqueue"
open_collective: "matiqueue"
ko_fi: "matiqueue"
tidelift: "npm/matiqueue"
community_bridge: "matiqueue-project"
liberapay: "matiqueue"
issuehunt: "matiqueue"
lfx_crowdfunding: "matiqueue-project"
polar: "matiqueue"
buy_me_a_coffee: "matiqueue"
thanks_dev: "matiqueue"
custom: [ "https://matiqueue.com/sponsor", "https://matiqueue.com/donate" ]
