name: Build Tauri + Next.js Desktop App

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # Możesz zmienić na windows-latest lub macos-latest w zależności od potrzeb

    steps:
      # Krok 1: Pobierz kod z repozytorium
      - name: Checkout repository
        uses: actions/checkout@v4

      # Krok 2: Zainstaluj Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Możesz zmienić wersję Node.js na tę, której używasz

      # Krok 3: Zainstaluj PNPM
      - name: Install PNPM
        run: npm install -g pnpm

      # Krok 4: Zainstaluj Rust
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy # Opcjonalne, możesz usunąć jeśli nie potrzebujesz

      # Krok 5: Zainstaluj zależności projektu
      - name: Install dependencies
        run: pnpm install

      # Krok 6: Zbuduj aplikację
      - name: Build application
        run: pnpm build

      # Opcjonalny krok: Archiwizacja buildów
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: desktop-app-build
          path: apps/desktop/src-tauri/release/
