name: Build Tauri + Next.js Desktop App

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Krok 1: Pobierz kod z repozytorium
      - name: Checkout repository
        uses: actions/checkout@v4

      # Krok 2: Zainstaluj zależności systemowe dla Tauriego na Ubuntu
      - name: Install system dependencies (Ubuntu)
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf libglib2.0-dev

      # Krok 3: Zainstaluj Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Krok 4: Zainstaluj PNPM
      - name: Install PNPM
        run: npm install -g pnpm

      # Krok 5: Zainstaluj Rust
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy

      # Krok 6: Zainstaluj zależności projektu
      - name: Install dependencies
        run: pnpm install

      # Krok 7: Zbuduj aplikację
      - name: Build application
        run: pnpm build

      # Opcjonalny krok: Archiwizacja buildów
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: desktop-app-build
          path: apps/desktop/src-tauri/release/
