name: Build Tauri + Next.js App

on:
  push:
    branches:
      - dev # lub zmień na inną gałąź, której używasz
  pull_request:
    branches:
      - main # lub zmień na inną gałąź, której używasz

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Możesz dostosować wersję Node.js

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
          source $HOME/.cargo/env

      - name: Install dependencies
        run: |
          pnpm install

      - name: Build the app
        run: |
          # Ustawienie folderu roboczego dla Tauri w monorepo (dostosuj ścieżkę, jeśli to konieczne)
          cd apps/desktop
          pnpm build # Budowanie aplikacji Next.js oraz Tauri w jednym kroku

      - name: Upload build artifacts (optional)
        uses: actions/upload-artifact@v2
        with:
          name: tauri-build
          path: apps/desktop/src-tauri/release/
